    sources:
      - BigShoulders.glyphs
    familyName: Big Shoulders
    # buildOTF: False
    # buildTTF: False
    axisOrder:
      - opsz
      - wght
    stat:
      BigShoulders[opsz,wght].ttf:
      - name: Optical size
        tag: opsz
        values:
        - name: Text
          value: 10
        - name: Display
          value: 72
          flags: 2
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800
        - name: Black
          value: 900
    # instances:
    #   BigShoulders[opsz,wght].ttf:
    #   - familyName: "Big Shoulders Text"
    #     # styleName: "Regular"
    #     coordinates:
    #       opsz: 10
    #       wght: 100